spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/boatmanagement
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
    # url: jdbc:postgresql://localhost:5432/boatmanagement
    # username: postgres
    # password: 123456
    # driver-class-name: org.postgresql.Driver
  application:
    name: BoatManagement

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'

# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: false
  # 配置接口文档的分组
  documents:
    - group: default
      name: 默认分组
      locations: classpath:markdown/*

jwt:
  signKey: sakurapuare
  expire: 604800
  # 7 days in seconds

server:
  port: 8123

wechat:
  miniapp:
    appId:
    appSecret: